server:
  port: 9090 
  
spring:
  application:
    name: Admin-Server
  thymeleaf:
    check-template-location: false
    
  devtools:
    livereload:
      enabled: false
  cache:
    type: caffeine

eureka:
  instance:
    hostname: localhost  # Set a proper hostname
    instance-id: ${eureka.instance.hostname}:${server.port}  # Unique instance ID
    prefer-ip-address: true  # Use IP instead of hostname
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL of Eureka Server
    register-with-eureka: true # Register Admin Server with Eureka
    fetch-registry: true  # Fetch service list from Eureka
    
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Exposes all actuator endpoints
  endpoint:
    health:
      show-details: always # Show detailed health info
      
  info:
    env:
      enabled: true # Enables environment info
  