package com.orderservice.dto;

import java.time.LocalDateTime;
import java.util.List;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class OrderResponseDTO {  // Order Service returns this to the client.
	
	private String orderId;          // UUID generated by the Order Service
	
    private Long userId;             // Extracted from the JWT token
    
    private String status;           // e.g., "PENDING", "CONFIRMED"
    
    private Double totalAmount;      // Sum of all item totals
    
    private String shippingAddress;  // Copied from the request
    
    private LocalDateTime createdAt; // Timestamp of order creation
    
    private List<OrderItemResponseDTO> items; // Details of ordered items

}
